version: '3.9'
services:
  db:
    image: mysql:8.0
    restart: always
    container_name: mysql-cont
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: root
      MYSQL_PASSWORD: password711
      MYSQL_ROOT_HOST: '%'